
version: v1

rules:
  status_code:
    enabled: true
    allowed_ranges: [200, 400]

  response_time:
    enabled: true
    max_ms: 3500

  headers:
    enabled: true
    required:
      - Content-Type

  empty_response:
    enabled: true

  json_schema:
    enabled: false
